name: ci
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build-docker-image:
    name: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: false
